#define SCREEN_WIDTH 230
#define SCREEN_HEIGHT 51
#define WINDOW_WIDTH 90
#define LEFT_BORDER_DISTANCE 50
#define RIGTH_BORDER_DISTANCE 50
#define MINIMUM_STAR_DUST 5
#define MAXIMUM_STAR_DUST 200
#define INITIAL_STAR_DUST 100
#define LEVELS 8
#define PORTALS 10
#define MAXIMUM_BAD_PORTALS 5
#define MINIMUM_BAD_PORTALS 3
#define BORDER_WIDTH 2
#define TITLE_X 90
#define TITLE_Y 1
#define RANKING_X 6
#define RANKING_Y 2
#define PORTALS_X 58
#define PORTALS_Y 14
#define CONTROLS_X 183
#define CONTROLES_Y 2
#define PLAYER_INFO_X 183
#define PLAYER_INFO_Y 18
#define PAYOUT_RATIO 1.2
#define DARK_MATTER_DETECTOR 3
#define CLIMATE_X 193
#define CLIMATE_Y 40
#define MENU_X 20
#define MENU_Y 12
#define ASCII_1_X 50
#define ASCII_1_Y 15
#define ASCII_2_X 140
#define ASCII_2_Y 15
#define PLANETS_X 8
#define PLANETS_Y 24